CREATE DATABASE IF NOT EXISTS BRDJ_USECASE_REFERENCE_FILES;
CREATE TABLE IF NOT EXISTS BRDJ_USECASE_REFERENCE_FILES.ACNT (
    ACNT_ID_NUM_KEY varchar(255),
    ACNT_ID_NUM varchar(255),
    ACNT_ID_TYP_CD varchar(255),
    ACNT_PRTY_REL varchar(255),
    ACNT_NUM varchar(255),
    PARNT_NSC_NUM varchar(255),
    ACNT_OPN_DT DATE,
    ACNT_NAME varchar(255),
    ACNT_STS_CD varchar(255),
    ACNT_CLSED_IND varchar(255),
    JURIS_CD varchar(255),
    SRC_SYS_ACNT_TYP varchar(255),
    SRC_SYS_ACNT_SUB_TYP varchar(255),
    ACNT_CCY_REF varchar(255),
    LDGR_BAL_EOD DECIMAL,
    ACNT_MRKT_CLAS_CD varchar(255),
    CUST_CR_CNTRL_STRTGY_CD varchar(255),
    BUS_CTR_CNTRLD_IND varchar(255),
    UNQ_ACNT_GRP_NUM varchar(255),
    ACNT_SUB_OFC_CD varchar(255),
    DR_INT_RATE_TYP varchar(255),
    DR_INT_RATE DECIMAL,
    ACNT_DATA_SRC_CD varchar(255),
    BATCH_PROCESS_NAME varchar(255),
    START_DATE TIMESTAMP,
    LAST_UPDT_DATE TIMESTAMP,
    RECORD_DELETED_FLAG TINYINT,
    ACNT_ROLE_UPDT_SEQ varchar(255),
    ACNT_ROLE_UPDT_DTTM TIMESTAMP,
    SHDW_BAL_AMT DECIMAL,
    SHDW_BAL_DTTM TIMESTAMP,
    SHDW_BAL_SEQ varchar(255),
    LDGR_BAL_AMT DECIMAL,
    LDGR_BAL_DTTM TIMESTAMP,
    LDGR_BAL_SEQ varchar(255)
);

--SELECT ACNT_ID_NUM, 
--    SHDW_BAL_AMT, 
--    SHDW_BAL_DTTM,
--    SHDW_BAL_SEQ, 
--    LDGR_BAL_AMT, 
--    LDGR_BAL_DTTM,
--    LDGR_BAL_SEQ FROM BRDJ_USECASE_REFERENCE_FILES.ACNT


CREATE TABLE IF NOT EXISTS BRDJ_USECASE_REFERENCE_FILES.OFFSET_MANAGER (
    TOPIC_NAME VARCHAR(255) NOT NULL,
    TOPIC_PARTITION VARCHAR(255) NOT NULL,
    TOPIC_OFFSET BIGINT,
    CONSTRAINT PK PRIMARY KEY (TOPIC_NAME, TOPIC_PARTITION)
);


CREATE TABLE IF NOT EXISTS BRDJ_USECASE_REFERENCE_FILES.STATS_MANAGER (
    AIRFLOW_WORKFLOW_NAME VARCHAR(255) NOT NULL,
    AIRFLOW_TASK_NAME VARCHAR(255),
    CONTROLM_WORKFLOW_NAME VARCHAR(255),
    CONTROLM_PROCESSED_DATE DATE,
    SPARK_CDE_RUN_ID VARCHAR(255),
    TOPIC_NAME VARCHAR(255),
    JSON_DATA VARCHAR(255),
    LOGGED_TIMESTAMP TIMESTAMP NOT NULL,
    CONSTRAINT PK PRIMARY KEY(AIRFLOW_TASK_NAME, LOGGED_TIMESTAMP)
);