CREATE SCHEMA IF NOT EXISTS ${prefix}brdj;

CREATE TABLE IF NOT EXISTS ${prefix}brdj.OFFSET_MANAGER (
    TOPIC_NAME VARCHAR(255) NOT NULL,
    TOPIC_PARTITION VARCHAR NOT NULL,
    TOPIC_OFFSET BIGINT,
    CONSTRAINT PK PRIMARY KEY (TOPIC_NAME, TOPIC_PARTITION),
);

CREATE TABLE IF NOT EXISTS BRDJ_USECASE_REFERENCE_FILES.OFFSET_MANAGER (
    TOPIC_NAME VARCHAR(255) NOT NULL,
    TOPIC_PARTITION VARCHAR(255) NOT NULL,
    TOPIC_OFFSET BIGINT,
    CONSTRAINT PK PRIMARY KEY (TOPIC_NAME, TOPIC_PARTITION)
);